### ISSUE TITLE
Single/Double Click not working.

### ISSUE THREAD

**Issue by miremo0** [sylvek/itracing2#106] opened 2017-05-02 22:21 UTC
I thought it was my iTag which is not working until I found out that..
It wasn't my iTag which is having an issue, I downloaded some iTag Apps where I can connect and do some functionalities with my iTag, and all other apps was working fine except this itracing2( I mean the clicking/changecharacteristics).

So how did I solved this issue?
Whenever the single/double click is not working, I open the other app name cTracing, I think you know that app, then I connect my iTag, then I go back to itracing2 and magically the single/double click functions is working..

So my conclusion is that, maybe sometimes the connection is lost?(Not sure tho because I can ring the iTag, just the clicks which is not working). 

I hope you can find a fix on this one, you have a great application bro, I might donate if ever this one will be solved. 

Thank you!

**Comment by sylvek** [comment] 2017-05-03 06:35
Hi @miremo0 thanks for your report.
It seems that iTag connection is exclusive and you should not be able to use it with 2 app'.
it is possible to do more tests when your iTag doesn't work? like.. take a screenshot of the device dashboard (with the circle green/red). It helps me to investigate more deeper.

Regards,
Sylvain

**Comment by miremo0** [comment] 2017-05-03 14:34
![image](https://cloud.githubusercontent.com/assets/20988954/25665574/9a92ccec-3050-11e7-9538-b5a5152cc13b.png)

**Comment by miremo0** [comment] 2017-05-03 14:51
Not sure tho, but I think the function sendAction has something to do. Hope we can fix it.

**Comment by sylvek** [comment] 2017-05-03 15:06
Thks, as i can see.. your iTag is gracefully recognized.. i'll check the differents scenario that could explain that.

**Comment by miremo0** [comment] 2017-05-03 15:06
Hoping for a quick fix, thank you so much dude!

**Comment by sylvek** [comment] 2017-05-06 06:32
the last version 2.4.1 fixes an issue around the double click .. maybe that fixes your issue alsoa

**Comment by peaceforall** [comment] 2017-05-13 21:31
I'm also having issues registering any single or double click with this app for my iTag. Other applications (like the original iTracing app ) seem to be able to pickup single and double-click fine. Other features, such as connecting and triggering the alarm seem to be working.

This is the model of iTag I'm using: https://www.aliexpress.com/item/1pcs-Wireless-Bluetooth-4-0-Tracker-Smart-iTag-Anti-lost-Child-Bag-Wallet-Key-Finder-Child/32612094616.html 

Please try to fix this when you can

**Comment by sylvek** [comment] 2017-05-13 21:51
Hi if you be able to scan your itag and send the service uuid, I could
check if the issue comes from it..

Le sam. 13 mai 2017 à 23:31, peaceforall <notifications@github.com> a
écrit :

**Comment by peaceforall** [comment] 2017-05-13 22:11
How do I do this? Please instruct and I can try and help you best I can

**Comment by miremo0** [comment] 2017-05-14 05:05
I think it's also on UUID.. can you also teach us on what to replace on the code? I mean to replace what characterchanged it detects? I use several apps to detect the UUID that comes from my iTag.

**Comment by miremo0** [comment] 2017-05-14 13:00
So I debug the app and analyze your code... The FIND_ME_SERVICE and FIND_ME_CHARACTERISTICS is the thing that should mind.

I used this app to analyze the UUID of my newly bought iTag and found out this UUID's.

![image](https://cloud.githubusercontent.com/assets/20988954/26033994/4c606552-38e8-11e7-922b-359765ab011e.png)

**Comment by sylvek** [comment] 2017-05-14 13:06
Hi. I think that the uuid inside itracing2 matches with yours.. So it
should work. I'll do more tests this week.. Hoping that I've not included a
regression in the last release.

**Comment by miremo0** [comment] 2017-05-14 13:17
This is the iTag that I'm having a problem:
![image](https://cloud.githubusercontent.com/assets/20988954/26034155/be301db0-38ea-11e7-9286-bbb1e8a731ac.png)

As you can see the UnknownService/Find_Me_Service is duplicate... Idk why..

**Comment by sylvek** [comment] 2017-05-14 17:01
okay ... i took a time to read your screenshots :)
it appears that your iTag does not have all features :-/
especially you don't have "immediate alert service" (00001802-0000-1000-8000-00805f9b34fb) that allows to play with single & double clicks.

services uuid are published here -> https://www.bluetooth.com/specifications/gatt/services

**Comment by miremo0** [comment] 2017-05-14 18:38
![image](https://cloud.githubusercontent.com/assets/20988954/26036799/9124811c-3917-11e7-96cb-a5c5b8f9d159.png)
![image](https://cloud.githubusercontent.com/assets/20988954/26036800/a09d35ee-3917-11e7-9b96-51cffbb0005a.png)

It has tho.

**Comment by sylvek** [comment] 2017-05-14 18:42
Ok, I'll add a debug mode inside the next release...

**Comment by peaceforall** [comment] 2017-05-14 23:55
Hi sylvek,
I believe I have found the cause of this issue. For some reason The keypress notifications are disabled when the device first connects. However if you send the "notifications enabled" to the device they will be enabled, and you can then receive keypresses from the tag.
![screenshot_19700527-165800](https://cloud.githubusercontent.com/assets/9010927/26038845/06e3612c-38c6-11e7-87e3-aa4a37a73d20.png)

**Comment by peaceforall** [comment] 2017-05-15 00:17
It seems that for whatever reason itracing2 is not doing this properly

**Comment by sylvek** [comment] 2017-05-15 08:42
nice job, i could force to enable it. It occurs each time? (meaning, every time you power on your iTag, or every time you pair it with itracing2?)

**Comment by sylvek** [comment] 2017-05-15 20:49
[app-release.apk.zip](https://github.com/sylvek/itracing2/files/1002447/app-release.apk.zip)

@peaceforall if you have time to test this fix.. (i wrote it totally in free style, 5min before sleeping..)

**Comment by peaceforall** [comment] 2017-05-15 21:55
Unfortunately it does not fix this issue for me

**Comment by sylvek** [comment] 2017-05-16 10:05
@peaceforall thks.. may you detail step by step what you need to do to successfully interact with your iTag?

**Comment by peaceforall** [comment] 2017-05-16 10:51
0. Install app "nRF Connect" on phone ( https://play.google.com/store/apps/detailsid=no.nordicsemi.android.mcp&hl=en )
1. Turn on the iTag, open the nRF Connect app. connect iTag to app
2. Browse to the service with UUID 0000fffe0-0000-1000-8000-00805f9b34fb:
![screenshot_19700529-035706](https://cloud.githubusercontent.com/assets/9010927/26102665/e2b39864-39ea-11e7-8bf0-d9c147277107.png)

3. Click the icon with the 3 downward arrows:
![screenshot_19700529-035713](https://cloud.githubusercontent.com/assets/9010927/26102669/e9a18fdc-39ea-11e7-8547-880a54e71c93.png)

4. Successfully use your iTag with iTracing2

**Comment by peaceforall** [comment] 2017-05-22 04:05
Do you need any help diagnosing or fixing this issue? Please let me know I'd be more than glad to help

**Comment by sylvek** [comment] 2017-06-05 06:28
Hey, I keep in mind to fix it but time is missing. I guess that you found
the trick with your diagnostic.

Le lun. 22 mai 2017 à 06:05, peaceforall <notifications@github.com> a
écrit :

**Comment by peaceforall** [comment] 2017-06-07 19:25
Hi Sylvek,
This is still not fixed. Unfortunately every time I have to turn on this iBeacon you have to enter this nrf connect app, connect to it, press this button, then connect your app to the beacon. If you turn off the iBeacon you will have to do this again. It would be a great help if you could try with this and I would be willing to pay you for your efforts

**Comment by sylvek** [comment] 2017-06-07 21:52
Ok thank you for your reports very helpful. I don't have time this current
days but I don't forget this issue. Your analysis is very precious. Thks
again

Le mer. 7 juin 2017 à 21:25, peaceforall <notifications@github.com> a
écrit :

**Comment by peaceforall** [comment] 2017-07-11 01:32
Hi Sylvain,
Why is this issue closed? It's still unresolved for me.

Please let me know I would be glad to help in any way I can

**Comment by sylvek** [comment] 2017-07-11 05:24
Hi, because i merged the code.. but the code is not yet available on the playstore.
please try the beta version https://play.google.com/apps/testing/net.sylvek.itracing2
and let me know if it's working :)

Sorry i'm on an huge project that take all my time :-/

**Comment by jderriks** [comment] 2018-01-03 12:07
Nice discussion, I have the same problem. To make the ITAG pushbutton work write 1 to 0x2901 with NRF Connect, then close NRF connect (or it will keep the itag locked) and start Itracing2 again and make sure the checkbox is ticked to keep a lock on the tag.
After turning the itag off and on again it still worked and the 2902 value says "notifications enabled".

**Comment by 9w2xne** [comment] 2021-04-15 01:51
hi, it seem some itag i purchased will not trigger double click. may i know how to verify this so can be helpful to improved this apps?

**Comment by sylvek** [comment] 2022-01-01 21:19
hi @9w2xne , sorry for the delay..

in fact, double click is coded on iTracing2 (https://github.com/sylvek/itracing2/blob/bc82601920763b4253575fa638840c91f053cd55/app/src/main/java/net/sylvek/itracing2/BluetoothLEService.java#L201)

if you can debug itracing2 your help will be very appreciated 🙏

**Closed** 2022-01-03 00:19 UTC
Labels: help wanted
