### ISSUE TITLE
Issue regarding simple and double clicks. 

### ISSUE THREAD

**Issue by FondSteam39** [sylvek/itracing2#90] opened 2017-01-02 13:23 UTC
Hi. 

I can make my itag beep from my phone but the simple click and double click do not register at all. The connect action does work. 

Thanks in advance

**Comment by sylvek** [comment] 2017-01-09 22:06
duplicate of #92  ?

**Comment by FondSteam39** [comment] 2017-01-10 16:11
Yes it is the same. I will follow that threads. Thanks.

**Comment by 35018197992** [comment] 2017-01-11 07:00
Hi sylvek I want to ask you why the application use stop ring start ring
vibration...  İts not working . We moved away from the mle15 if we touch
microphone mark we hear bip voice.
Second quuestion the distance must be several for the warning

10 Oca 2017 00:06 tarihinde "Sylvain M." <notifications@github.com> yazdı:

**Comment by sylvek** [comment] 2017-01-11 07:33
Hi... If you have an mle15, it should work. I have done a test yesterday
and everything worked. May you send me some screenshot of your itracing 2?

I can do nothing about distance.. The signal strength between your phone
and you mle15 is used internally by Android to detect if the link is lost
or not.

Regards

Le mer. 11 janv. 2017 08:00, 35018197992 <notifications@github.com> a
écrit :

**Closed** 2017-03-11 13:57 UTC
